// ─── GroceryList + GroceryItem ────────────────────────────────────────────────
//
// Grocery list derived from a MealPlan. Generated by the `generate-meal-plan`
// Edge Function alongside the plan, or on demand via the Grocery List screen.
//
// Each item is categorised (produce, protein, dairy, pantry, etc.) so the
// list can be grouped and sorted in a supermarket-friendly order.
//
// DB table: grocery_lists
//   id              uuid PK
//   user_id         uuid FK → auth.users
//   meal_plan_id    uuid FK → meal_plans (nullable — list can exist standalone)
//   week_start      date
//   items           jsonb   (array of GroceryItem)
//   is_shared       bool    default false
//   share_token     text    unique (used for Instacart / Amazon Fresh integration)
//   created_at      timestamptz

enum GroceryCategory {
  produce,
  protein,
  dairy,
  grains,
  pantry,
  condiments,
  beverages,
  frozen,
  other;

  String get label => switch (this) {
        GroceryCategory.produce     => 'Produce',
        GroceryCategory.protein     => 'Protein',
        GroceryCategory.dairy       => 'Dairy',
        GroceryCategory.grains      => 'Grains & Bread',
        GroceryCategory.pantry      => 'Pantry',
        GroceryCategory.condiments  => 'Condiments & Sauces',
        GroceryCategory.beverages   => 'Beverages',
        GroceryCategory.frozen      => 'Frozen',
        GroceryCategory.other       => 'Other',
      };

  String get emoji => switch (this) {
        GroceryCategory.produce     => '🥦',
        GroceryCategory.protein     => '🍗',
        GroceryCategory.dairy       => '🥛',
        GroceryCategory.grains      => '🍞',
        GroceryCategory.pantry      => '🫙',
        GroceryCategory.condiments  => '🫒',
        GroceryCategory.beverages   => '🧃',
        GroceryCategory.frozen      => '🧊',
        GroceryCategory.other       => '🛒',
      };

  /// Sort order: produce first, other last.
  int get sortOrder => index;
}

class GroceryItem {
  final String id;
  final String name;
  final String quantity;   // e.g. "200g", "2 pieces", "1 cup"
  final GroceryCategory category;
  final bool isChecked;
  /// Which meal(s) in the plan use this ingredient (for context).
  final List<String> usedInMeals;

  const GroceryItem({
    required this.id,
    required this.name,
    required this.quantity,
    required this.category,
    this.isChecked = false,
    this.usedInMeals = const [],
  });

  GroceryItem copyWith({bool? isChecked}) => GroceryItem(
        id: id,
        name: name,
        quantity: quantity,
        category: category,
        isChecked: isChecked ?? this.isChecked,
        usedInMeals: usedInMeals,
      );

  factory GroceryItem.fromMap(Map<String, dynamic> map) => GroceryItem(
        id: (map['id'] as String?) ?? map.hashCode.toString(),
        name: (map['name'] as String?) ?? '',
        quantity: (map['quantity'] as String?) ?? '',
        category: GroceryCategory.values.firstWhere(
          (e) => e.name == (map['category'] as String? ?? 'other'),
          orElse: () => GroceryCategory.other,
        ),
        isChecked: (map['is_checked'] as bool?) ?? false,
        usedInMeals: (map['used_in_meals'] as List<dynamic>?)
                ?.map((e) => e as String)
                .toList() ??
            [],
      );

  Map<String, dynamic> toMap() => {
        'id': id,
        'name': name,
        'quantity': quantity,
        'category': category.name,
        'is_checked': isChecked,
        'used_in_meals': usedInMeals,
      };
}

class GroceryList {
  final String id;
  final String userId;
  final String? mealPlanId;
  final DateTime weekStart;
  final List<GroceryItem> items;
  final bool isShared;
  final String? shareToken;
  final DateTime createdAt;

  const GroceryList({
    required this.id,
    required this.userId,
    this.mealPlanId,
    required this.weekStart,
    required this.items,
    this.isShared = false,
    this.shareToken,
    required this.createdAt,
  });

  int get totalItems => items.length;
  int get checkedItems => items.where((i) => i.isChecked).length;
  double get progress =>
      totalItems == 0 ? 0.0 : checkedItems / totalItems;

  /// Items grouped by category, sorted in supermarket order.
  Map<GroceryCategory, List<GroceryItem>> get groupedItems {
    final map = <GroceryCategory, List<GroceryItem>>{};
    for (final item in items) {
      map.putIfAbsent(item.category, () => []).add(item);
    }
    // Sort by category's natural supermarket order.
    return Map.fromEntries(
      map.entries.toList()
        ..sort((a, b) => a.key.sortOrder.compareTo(b.key.sortOrder)),
    );
  }

  GroceryList withUpdatedItem(GroceryItem updated) => GroceryList(
        id: id,
        userId: userId,
        mealPlanId: mealPlanId,
        weekStart: weekStart,
        items: items.map((i) => i.id == updated.id ? updated : i).toList(),
        isShared: isShared,
        shareToken: shareToken,
        createdAt: createdAt,
      );

  factory GroceryList.fromMap(Map<String, dynamic> map) => GroceryList(
        id: map['id'] as String,
        userId: map['user_id'] as String,
        mealPlanId: map['meal_plan_id'] as String?,
        weekStart: DateTime.parse(map['week_start'] as String),
        items: (map['items'] as List<dynamic>? ?? [])
            .map((i) => GroceryItem.fromMap(i as Map<String, dynamic>))
            .toList(),
        isShared: (map['is_shared'] as bool?) ?? false,
        shareToken: map['share_token'] as String?,
        createdAt: DateTime.parse(map['created_at'] as String),
      );
}
